name: medicare
description: Doctor Appointment App
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.14.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  http:
  flutter_spinkit: ^5.2.0 
  webview_flutter: any  
  flutter_lints: ^1.0.0
  flutter_phone_direct_caller: 
  url_launcher: 
flutter:
  uses-material-design: true
  assets:
    - assets/
